// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDIhQz6EPiR_gKJ_QtMr1YadwIhnhxdco',
    appId: '1:748162836660:web:55586dfcb8446f3e174fe1',
    messagingSenderId: '748162836660',
    projectId: 'flutter-test-561f1',
    authDomain: 'flutter-test-561f1.firebaseapp.com',
    storageBucket: 'flutter-test-561f1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_xdW6vn-Dp7wb26wqWjXjJ5Xw6xCLyUw',
    appId: '1:748162836660:android:bab53d5fa9ebbbbb174fe1',
    messagingSenderId: '748162836660',
    projectId: 'flutter-test-561f1',
    storageBucket: 'flutter-test-561f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHT_G6W4smcDW7szCNXxmXDRo3CxumMQU',
    appId: '1:748162836660:ios:dd904e953a85636e174fe1',
    messagingSenderId: '748162836660',
    projectId: 'flutter-test-561f1',
    storageBucket: 'flutter-test-561f1.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHT_G6W4smcDW7szCNXxmXDRo3CxumMQU',
    appId: '1:748162836660:ios:dd904e953a85636e174fe1',
    messagingSenderId: '748162836660',
    projectId: 'flutter-test-561f1',
    storageBucket: 'flutter-test-561f1.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
